# Generated by Django 5.0.6 on 2024-06-27 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('primary_cuisine', models.CharField(blank=True, max_length=255)),
                ('overall_rating', models.FloatField(blank=True, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(max_length=255)),
                ('rating_type', models.CharField(max_length=10)),
                ('customer_experience', models.CharField(blank=True, max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='restaurant_recommender.restaurant')),
            ],
            options={
                'verbose_name': 'Aspect',
                'verbose_name_plural': 'Aspects',
            },
        ),
    ]
