# Generated by Django 5.0.6 on 2024-06-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspect',
            name='customer_experience',
        ),
    ]
