# Generated by Django 5.0.6 on 2024-07-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0003_remove_aspect_customer_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspect',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
