# Generated by Django 5.0.6 on 2024-07-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0005_alter_aspect_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
