# Generated by Django 5.0.6 on 2024-07-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0007_predictionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('dewpoint', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
        ),
    ]
