# Generated by Django 5.0.6 on 2024-07-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_recommender", "0008_weatherdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="location_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
