# Generated by Django 5.0.6 on 2024-07-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0009_restaurant_location_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aspect',
            index=models.Index(fields=['restaurant'], name='restaurant__restaur_fa65dd_idx'),
        ),
        migrations.AddIndex(
            model_name='aspect',
            index=models.Index(fields=['aspect'], name='restaurant__aspect_4e76d4_idx'),
        ),
        migrations.AddIndex(
            model_name='aspect',
            index=models.Index(fields=['rating_type'], name='restaurant__rating__c02bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionmodel',
            index=models.Index(fields=['model_name'], name='restaurant__model_n_e29be9_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionmodel',
            index=models.Index(fields=['restaurant'], name='restaurant__restaur_8cebbd_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionmodel',
            index=models.Index(fields=['is_active'], name='restaurant__is_acti_460552_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionmodel',
            index=models.Index(fields=['updated_at'], name='restaurant__updated_64d37a_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['restaurant_name'], name='restaurant__restaur_7898a3_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['primary_cuisine'], name='restaurant__primary_2cfe39_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['overall_rating'], name='restaurant__overall_2a37e3_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['neighborhood'], name='restaurant__neighbo_9e2620_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['zone'], name='restaurant__zone_068748_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['location_id'], name='restaurant__locatio_3a8721_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['timestamp'], name='restaurant__timesta_7a44ba_idx'),
        ),
    ]
