# Generated by Django 5.0.6 on 2024-07-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0012_alter_restaurant_hours_of_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='parking_details',
        ),
    ]
