# Generated by Django 5.0.6 on 2024-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0013_remove_restaurant_parking_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
