# Generated by Django 5.0.6 on 2024-07-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0014_alter_restaurant_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='awards',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='public_transit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
