# Generated by Django 5.0.6 on 2024-07-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0015_restaurant_awards_restaurant_public_transit'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
