# Generated by Django 5.0.6 on 2024-07-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0016_restaurant_photo_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurant__locatio_3a8721_idx',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='hours_of_operation',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='parking_information',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='payment_options',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='public_transit',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='seating',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='negative_aspects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='positive_aspects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
