# Generated by Django 5.0.6 on 2024-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0017_remove_restaurant_restaurant__locatio_3a8721_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
