# Generated by Django 5.0.6 on 2024-07-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0019_restaurant_address_restaurant_ambience_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='negative_aspects',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='positive_aspects',
        ),
    ]
