# Generated by Django 5.0.6 on 2024-07-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0022_remove_restaurant_positive_aspects'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurant__neighbo_9e2620_idx',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='neighborhood',
        ),
    ]
