# Generated by Django 5.0.6 on 2024-07-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0023_remove_restaurant_restaurant__neighbo_9e2620_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
