# Generated by Django 5.0.6 on 2024-07-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0024_alter_restaurant_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
