# Generated by Django 5.0.6 on 2024-07-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0025_alter_restaurant_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
