# Generated by Django 5.0.6 on 2024-07-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0026_alter_restaurant_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
    ]
