# Generated by Django 5.0.6 on 2024-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0027_remove_restaurant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
