# Generated by Django 5.0.6 on 2024-07-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0028_restaurant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='photo_url',
        ),
    ]
