# Generated by Django 5.0.6 on 2024-07-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0029_remove_restaurant_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
