# Generated by Django 5.0.6 on 2024-06-22 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('surname', models.CharField(max_length=32, verbose_name='Surname')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('groups', models.ManyToManyField(related_name='user_management_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='user_management_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user_management',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(blank=True, max_length=255, verbose_name='Cuisine preference')),
                ('restaurants', models.JSONField(blank=True, default=list)),
                ('menu', models.JSONField(blank=True, default=list)),
                ('rest_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('rest_long', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmark',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=32, verbose_name='First name')),
                ('surname', models.CharField(blank=True, max_length=32, verbose_name='Surname')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
