# Generated by Django 5.0.6 on 2024-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0007_predictionmodel'),
        ('user_management', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='rest_lat',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='rest_long',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='restaurants',
            field=models.ManyToManyField(related_name='user_preferences', to='restaurant_recommender.restaurant'),
        ),
    ]
