# Generated by Django 5.0.6 on 2024-07-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_bookmark_cuisine_remove_bookmark_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='restaurants',
        ),
    ]
