# Generated by Django 5.0.6 on 2024-07-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0007_predictionmodel'),
        ('user_management', '0006_remove_bookmark_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='restaurants',
            field=models.ManyToManyField(related_name='user_preferences', to='restaurant_recommender.restaurant'),
        ),
    ]
