# Generated by Django 5.0.6 on 2024-07-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_bookmark_restaurants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
