# Generated by Django 5.0.6 on 2024-07-08 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0007_predictionmodel'),
        ('user_management', '0009_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='restaurants',
            field=models.ManyToManyField(related_name='bookmarks', to='restaurant_recommender.restaurant'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
