# Generated by Django 5.0.6 on 2024-07-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_bookmark_restaurants_alter_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
