# Generated by Django 5.0.6 on 2024-07-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurant_recommender', '0009_restaurant_location_id'),
        ('user_management', '0011_bookmark_last_accessed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user'], name='bookmark_user_id_c654d1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactus',
            index=models.Index(fields=['user'], name='user_manage_user_id_967ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='contactus',
            index=models.Index(fields=['email'], name='user_manage_email_8413d6_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='user_profil_user_id_4f95f8_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['slug'], name='user_profil_slug_2e81aa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_manage_email_55611d_idx'),
        ),
    ]
