# Generated by Django 5.0.6 on 2024-07-18 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_bookmark_bookmark_user_id_c654d1_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookmark',
            new_name='preference__user_id_558b60_idx',
            old_name='bookmark_user_id_c654d1_idx',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='dress_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='positive_aspects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='primary_cuisine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table='preference_bookmark',
        ),
    ]
