# Generated by Django 5.0.6 on 2024-07-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_rename_bookmark_user_id_c654d1_idx_preference__user_id_558b60_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='dress_code',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='positive_aspects',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='primary_cuisine',
        ),
    ]
