# Generated by Django 5.0.6 on 2024-07-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0022_remove_restaurant_positive_aspects'),
        ('user_management', '0015_bookmark_dress_code_bookmark_positive_aspects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='restaurant_recommender.restaurant'),
        ),
    ]
