# Generated by Django 5.0.6 on 2024-07-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_rename_restaurants_bookmark_restaurant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='restaurant_name',
            new_name='restaurants',
        ),
    ]
