# Generated by Django 5.0.6 on 2024-07-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_rename_restaurant_name_bookmark_restaurants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='restaurants',
            new_name='restaurant_name',
        ),
    ]
