# Generated by Django 5.0.6 on 2024-07-18 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_rename_restaurants_bookmark_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
