# Generated by Django 5.0.6 on 2024-07-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_alter_bookmark_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='restaurant_name',
            new_name='restaurants',
        ),
    ]
