# Generated by Django 5.0.6 on 2024-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_recommender', '0027_remove_restaurant_price'),
        ('user_management', '0022_preference_userlikedrestaurant_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='positive_aspects',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.AddIndex(
            model_name='preference',
            index=models.Index(fields=['type'], name='user_manage_type_1829a1_idx'),
        ),
        migrations.AddIndex(
            model_name='userlikedrestaurant',
            index=models.Index(fields=['user'], name='user_manage_user_id_41cc5f_idx'),
        ),
        migrations.AddIndex(
            model_name='userlikedrestaurant',
            index=models.Index(fields=['restaurant'], name='user_manage_restaur_e2580b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user'], name='user_manage_user_id_11906b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['preference'], name='user_manage_prefere_c59b63_idx'),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
